services:
  backend:
    build: ./backend
    container_name: consumesafe-backend
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/db:/app/src/db
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    container_name: consumesafe-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:5050
    depends_on:
      - backend
    restart: unless-stopped
